name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set TAG
        id: vars
        run: echo "TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: yanggino
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Print Docker Tag Info
        run: |
          echo "Preparing to push image to Docker Hub:"
          echo "Repository: yanggino/2025cloud"
          echo "Tag: ${{ steps.vars.outputs.TAG }}"

      - name: Build
        run: |
            docker build -t yanggino/2025cloud:${{ steps.vars.outputs.TAG }} .
            docker build -t yanggino/2025cloud:latest .
            
      - name: Push
        run: |
            docker push yanggino/2025cloud:${{ steps.vars.outputs.TAG }}
            docker push  yanggino/2025cloud:latest
